name: superapp
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"


dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.4
  go_router: ^13.0.1
  intl: ^0.18.1
  latlong2: ^0.9.1
  lottie: ^3.1.2


dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0


flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/fonts/euclid-circular-a-cufonfonts/
    - assets/animation/
    - assets/png/
    - assets/rooms/
    - assets/svg/


  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Bold.ttf
          weight: 700
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Bold_Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Italic.ttf
          style: italic
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Light.ttf
          weight: 300
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Light_Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Medium.ttf
          weight: 500
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Medium_Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_Regular.ttf
          weight: 400
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/euclid-circular-a-cufonfonts/Euclid_Circular_A_SemiBold_Italic.ttf
          weight: 600
          style: italic